apiVersion: v1
kind: Service
metadata:
  name: ihub-inventory-service
spec:
  selector:
    app: ihub-inventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # or NodePort if using locally
